import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Bungee } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
  preload: true
});

const bungee = Bungee({
  subsets: ["latin"],
  variable: "--font-bungee",
  display: "swap",
  weight: ["400"],
  preload: true
});

export const metadata: Metadata = {
  title: "ThermoChem",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${bungee.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
